name: Keep HF Space Awake

on:
  schedule:
    - cron: '0 0 * * *' # Runs every 24 hours
  workflow_dispatch:   # This adds the manual "Play" button

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Hugging Face
        run: curl -I https://saqibmurtaza-chainlit-shopping-agent.hf.space
      - name: Ping All Spaces
        run: |
          echo "Pinging Shopping Agent..."
          curl -I https://saqibmurtaza-chainlit-shopping-agent.hf.space
          
          echo "Pinging Student AI..."
          curl -I https://saqibmurtaza-student-ai-tool.hf.space
          
